[project]
name = "wox-plugin-host"
version = "0.0.1"
description = "Python host for Wox plugins"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru",
    "websockets",
    "wox-plugin==0.0.28",
]
