package plugin

import (
	"wox/common"
)

type WoxPreviewType = string
type WoxPreviewScrollPosition = string

const (
	WoxPreviewTypeMarkdown = "markdown"
	WoxPreviewTypeText     = "text"
	WoxPreviewTypeImage    = "image" // when type is image, data should be WoxImage.String()
	WoxPreviewTypeUrl      = "url"
	WoxPreviewTypeFile     = "file" // when type is file(can be *.md, *.jpg, *.pdf and so on), data should be url/filepath
	// file_list keeps multi-file selection data structured. Markdown path lists
	// were hard to scan and could not support a modern filename/directory layout
	// in the UI without brittle string parsing.
	WoxPreviewTypeFileList = "file_list"
	WoxPreviewTypeRemote   = "remote" // when type is remote, data should be url to load WoxPreview
	WoxPreviewTypeTerminal = "terminal"
	WoxPreviewTypeWebView  = "webview" // when type is webview, data should be JSON string of WoxPreviewWebviewData

	// internal use
	WoxPreviewTypePluginDetail = "plugin_detail" // when type is plugin_detail, data should be JSON string of plugin metadata
	WoxPreviewTypeChat         = "chat"          // when type is chat, data should be Json string of common.AIChatData. this type is only for ai chat plugin
	WoxPreviewTypeUpdate       = "update"        // internal update UI, data should be JSON string
	// ai_stream keeps model reasoning separate from the final answer. Markdown
	// blockquotes made reasoning and answer compete visually, while a structured
	// payload lets the UI keep the same text-preview frame and style reasoning
	// as lower-priority context.
	WoxPreviewTypeAIStream = "ai_stream"
	// query_requirement_settings is generated by core when plugin metadata declares
	// missing query prerequisites. The UI renders it as a focused settings form
	// instead of letting grid/list result density hide the actionable problem.
	WoxPreviewTypeQueryRequirementSettings = "query_requirement_settings"
)

const (
	WoxPreviewScrollPositionBottom = "bottom" // scroll to bottom after preview first show
)

type WoxPreview struct {
	PreviewType WoxPreviewType
	PreviewData string
	// PreviewOverlayData is the optional full-size image payload used when the UI opens an image
	// preview in the native overlay. PreviewData often points at a lightweight thumbnail, which is
	// correct for the inline preview but not enough for the click-to-enlarge flow.
	PreviewOverlayData string
	PreviewProperties  map[string]string // key support i18n
	ScrollPosition     WoxPreviewScrollPosition
}

func (p *WoxPreview) IsEmpty() bool {
	return p.PreviewData == ""
}

type WoxPreviewChatData struct {
	Conversations []common.Conversation
	Model         common.Model
}

type WoxPreviewWebviewData struct {
	Url           string `json:"url"`
	InjectCss     string `json:"injectCss,omitempty"`
	CacheDisabled bool   `json:"cacheDisabled,omitempty"`
}
