name: build

on:
  push:
    branches:
      - v2

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: crowdin_i18n
          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_labels: 'i18n'
          pull_request_assignees: 'crowdin-bot'
          pull_request_reviewers: 'qianlifeng'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: just test
      - name: Build
        run: just build all
#      - name: Upload linux-x64 artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: wox-linux-x64
#          path: publish/wox-linux-x64
#      - name: Upload win-x64 artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: wox-win-x64.exe
#          path: publish/wox-win-x64.exe
#      - name: Upload osx-x64 artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: wox-osx-x64.app
#          path: publish/wox-osx-x64.app/
#      - name: Upload osx-arm64 artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: wox-osx-arm64.app
#          path: publish/wox-osx-arm64.app/               