name: build

on:
  push:
    branches:
      - golang

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - name: Build darwin release
        run: just release darwin