name: build

on:
  push:
    branches:
      - v2

jobs:
  build-macos:
    runs-on: [ self-hosted, macOS ]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: just release darwin
  build-windows:
    runs-on: [ self-hosted, Windows ]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: just release windows